### ISSUE TITLE
FakerTrait error

### ISSUE THREAD

**Issue by NickNiceGuy** [cinghie/yii2-paypal#2]
Hi, there is a problem in Demo.php file at line 34.
The class use a trait, but Faker Trait ('cinghie\traits\FakerTrait') does not exist nowhere.
The error is NotFoundException

Any suggestion?
Thanks in advance

**Comment by cinghie** [comment]
Hi @nickhal ,

i have updated yii2-traits version; now the FakerTrait is in stable version.
I advise you to insert in the yii root composer.json, in "require-dev" section:
`"cinghie/yii2-traits": "@dev"`
